name: Trigger auto deployment for container-app-fplmy2m5rnaok

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-fplmy2m5rnaok-AutoDeployTrigger-96f870f8-5e48-469e-8058-1c9cacd81ccd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPFPLMY2M5RNAOK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPFPLMY2M5RNAOK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPFPLMY2M5RNAOK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPFPLMY2M5RNAOK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPFPLMY2M5RNAOK_REGISTRY_PASSWORD }}
          containerAppName: container-app-fplmy2m5rnaok
          resourceGroup: expresssampleb2b1b62b
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


